### ISSUE TITLE
what is the point of the project?

### ISSUE THREAD

**Issue by flyingfz** [thrinz/pgapi-starter-template#1]
i think  postgrest  is better .
http://postgrest.org/en/v5.1/

**Comment by thrinz** [comment]
Postgrest is a great Project. The current release of pgAPI does not have the complete intended functionality . I will highlight some of the upcoming features and explain how pgAPI is different from postgRest .
1.  postgrest works with a single database. If you want to access more than one database you would need to deploy another postgrest server. In pgAPI you can connect to multiple database connections and generate named REST API endpoints
2. pgAPI will be having the below functionalities intended for future
  a. Authentication and Authorization of the Webservices - restrict who has access to what APIs. The Authentication will be based on JWT and will be compliant with strong encryption , brute force attack prevention , rigid paasword policy compliance - everything configurable
  b. Integration to AWS S3 to enable ability to create REST API to save files like images  , files etc
  c.  Email Templates - Ability for the users to use templates and send emails as post route activity. 
  d.  Integration with twilio for SMS 
  e.  Integration with firebase for Push Notifications
  f.   Integration with Authentication Protocols like OpenID (keycloak) , OAuth2
and much more. 

Since i am the only developer working on this initiative , the progress is relatively lean , However i get help from the community , we can achieve this milestone in a shorter period.  I hope i have elaborated the intent of this project and its difference from postgrest. Postgrest has much more features than this current release but path of this project is little different from postgrest.  

Thanks for visiting this repository.

**Comment by flyingfz** [comment]
👍 。
